services:
  app:
    image: spotify-websocket:latest
    restart: always
    env_file:
      - .env
    networks:
      - traefik_public
    labels:
      - "traefik.http.routers.spotifyhook.rule=Host(`api.davlin.io`) && Method(`GET`, `POST`) && PathPrefix(`/v1/spotify-websocket`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.spotifyhook.loadbalancer.server.port=8000"
      - "traefik.http.routers.spotifyhook.entrypoints=https"
      - "traefik.http.routers.spotifyhook.tls=true"

networks:
  traefik_public:
    external: true
